services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    build: .
    # image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      GHUSER: ${GHUSER}
      GHBEARER: ${GHBEARER}
      GENURL: ${GENURL}
      ZIP_PASSWORD: ${ZIP_PASSWORD}
      GHBRANCH: ${GHBRANCH}
      PROTOCOL: ${PROTOCOL}
      REPONAME: ${REPONAME}
